title: Brewery Workers Union
title-on-all-pages: false

plugins:
  - jekyll-remote-theme
remote_theme: daattali/beautiful-jekyll

social-network-links:
  email: breweryworkers@iww.org.uk
  bluesky: breweryunion.bsky.social
